
server:
  port: 1234

#logging:
#  file: eticaretrestapi.log
#  level:
#    root: warn
#    org.springframework.web: debug
#    org.hibernate: error

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filterData
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true

application-description: ARABAMARKA Otomosyonu
application-version: 1.0